apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: customdomains.stable.example.com
  # either Namespaced or Cluster
spec:
#  scope: Namespaced
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: customdomains
    # singular name to be used as an alias on the CLI and for display
    singular: customdomain
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: CustomDomain
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - cd
  # group name to use for REST API: /apis/<group>/<version>
  group: stable.example.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                secret:
                  type: string
                hostedZoneName:
                  type: string
                zoneId:
                  type: string
                appsEndpoint:
                  type: string
            status:
              type: object
              properties:
                message:
                  type: string
                discoveredDomain:
                  type: string
                discoveredAppsEndpoint:
                  type: string
