kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: access-customdomain
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: access-customdomain
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated

